// angular-app/src/app/product-list/product-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductService } from '../product.service';

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.css']
})
export class ProductListComponent implements OnInit {
  products: any[] = [];
  filterTerm: string = '';

  constructor(private productService: ProductService) { }

  ngOnInit(): void {
    this.fetchProducts();
  }

  fetchProducts(): void {
    this.productService.getProducts().subscribe(
      data => {
        // Filter out products with null or empty image_downloads
        const filteredProducts = data.filter(product => 
          product.image_downloads !== null && 
          product.image_downloads.length > 0 &&
          (this.filterTerm === '' || product.terms.includes(this.filterTerm))
        );

        // Loop through the filtered products and clean up the image_downloads
        const cleanedProducts = filteredProducts.map(product => {
          return {
            ...product,
            // Remove [ and ' from image_downloads
            image_downloads: product.image_downloads.replace(/[\[\]']/g, '').split(', ')
          };
        });
        this.products = cleanedProducts;
      },
      error => {
        console.error('Error fetching products:', error);
      }
    );
  }
}
<h1>Produkter</h1>
<div class='filter-container'>
  <label for="filter" class="filter-label">Filter:</label>
  <select id="filter" class="filter-select" [(ngModel)]="filterTerm" (change)="fetchProducts()">
    <option value="">All</option>
    <option value="backpack">Backpack</option>
    <option value="bags">Bags</option>
    <option value="cardigans">Cardigans</option>
    <option value="cargo">Cargo</option>
    <option value="dresses">Dresses</option>
    <option value="hoodies">Hoodies</option>
    <option value="jackets">Jackets</option>
    <option value="jeans">Jeans</option>
    <option value="knitwear">Knitwear</option>
    <option value="linen">Linen</option>
    <option value="pants">Pants</option>
    <option value="puffers">Puffers</option>
    <option value="shoes">Shoes</option>
    <option value="shorts">Shorts</option>
    <option value="skirts">Skirts</option>
    <option value="suits">Suits</option>
    <option value="sweaters">Sweaters</option>
    <option value="t-shirts">T-shirts</option>
    <option value="tops">Tops</option>
  </select>
</div>

<div class="product-list">
  <div *ngFor="let product of products" class="product">
    <a [routerLink]="'/product/' + product.sku">
      <ng-container *ngIf="product.image_downloads.length > 0; else noImage">
        <img [src]="'./assets/mango/' + product.image_downloads[0] + '.jpg'" [alt]="product.name">
      </ng-container>
      
      <ng-template #noImage>
        <div>No Image Available</div>
      </ng-template>
    </a>
    <p class="product-content">{{ product.name }}</p>
    <p class="product-content">Pris: {{ product.price }} {{ product.currency }}</p>
  </div>
</div>

// react-app/src/components/ProductList.js
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';

const ProductList = () => {
  const [products, setProducts] = useState([]);
  const [limit] = useState(400);
  const [filterTerm, setFilterTerm] = useState(null);

  useEffect(() => {
    let apiUrl = 'http://localhost:3001/api/products';
    if (filterTerm) {
      apiUrl += `?term=${filterTerm}`;
    }
  
    fetch(apiUrl)
      .then(response => response.json())
      .then(data => {
        // Filter out products with null or empty image_downloads
        const filteredProducts = data.filter(product => product.image_downloads !== null && product.image_downloads.length > 0);

        // Loop through the filtered products and clean up the image_downloads
        const cleanedProducts = filteredProducts.map(product => {
          return {
            ...product,
            // Remove [ and ' from image_downloads
            image_downloads: product.image_downloads.replace(/[\[\]']/g, '').split(', ')
          };
        });
        setProducts(cleanedProducts);
      })
      .catch(error => console.error('Error fetching products:', error));
  }, [limit, filterTerm]);

  const handleFilterChange = (event) => {
    setFilterTerm(event.target.value);
  };

  const filterProducts = (product) => {
    if (!filterTerm) return true; // Om ingen term är vald, returnera true för att visa alla produkter
    return product.terms.includes(filterTerm);
  };

  return (
    <div>
      <h1>Produkter</h1>
      <div>
        <label htmlFor="filter">Filter:</label>
        <select id="filter" onChange={handleFilterChange}>
          <option value="">Alla</option>
          <option value="backpack">Ryggsäck</option>
          <option value="bags">Väskor</option>
          <option value="cardigans">Cardigans</option>
          <option value="cargo">Cargo</option>
          <option value="dresses">Klänningar</option>
          <option value="hoodies">Hoodies</option>
          <option value="jackets">Jackor</option>
          <option value="jeans">Jeans</option>
          <option value="knitwear">Knitwear</option>
          <option value="linen">Linen</option>
          <option value="pants">Byxor</option>
          <option value="puffers">Puffers</option>
          <option value="shoes">Skor</option>
          <option value="shorts">Shorts</option>
          <option value="skirts">Kjolar</option>
          <option value="suits">Kavaj</option>
          <option value="sweaters">Sweaters</option>
          <option value="t-shirts">T-shirts</option>
          <option value="tops">Toppar</option>
        </select>
      </div>
      <div className="product-list">
        {products.filter(filterProducts).map(product => (
        <div key={product.sku} className="product">
          <Link to={`/product/${product.sku}`}>
            {product.image_downloads.length > 0 ? (
              <img
                src={require(`../../../mango/${product.image_downloads[0]}.jpg`)}
                alt={product.name}
                className="product-content"
                id="product-image"
              />
            ) : (
              <div>No Image Available</div>
            )}
          </Link>
          <p className="product-content">{product.name}</p>
          <p className="product-content">Pris: {product.price} {product.currency}</p>
        </div>
        ))}
      </div>
    </div>
  );
};

export default ProductList;
