// angular-app/src/app/shopping-cart/shopping-cart.component.ts
import { Component } from '@angular/core';
import { CartService } from '../cart.service';

@Component({
  selector: 'app-shopping-cart',
  templateUrl: './shopping-cart.component.html',
  styleUrls: ['./shopping-cart.component.css']
})
export class ShoppingCartComponent {
  constructor(private cartService: CartService) {}

  get cart(): any[] {
    return this.cartService.getCart();
  }

  removeFromCart(sku: string): void {
    this.cartService.removeFromCart(sku);
  }

  calculateTotalPrice(): number {
    return this.cart.reduce((total, product) => total + parseFloat(product.price), 0);
  }
}
<div *ngIf="cart.length > 0; else emptyCart">
  <div *ngFor="let product of cart" class="shopping-cart-container">
    <div class="shopping-cart">
      <img [src]="'./assets/mango/' + product.image_downloads[0] + '.jpg'" alt="Bild" class="cart-image">
    </div>
    <div class="shopping-product-info">
      <p class="shopping-detail-content">{{ product.name }}</p>
      <p class="shopping-detail-content">Pris: {{ product.price }} {{ product.currency }}</p>
      <button (click)="removeFromCart(product.sku)">Ta bort</button>
    </div>
  </div>
  <div class="total-price">
    <p>Totalt pris: {{ calculateTotalPrice() }} {{ cart[0].currency }}</p>
    <button class="pay-button">Betala</button>
  </div>
</div>

<ng-template #emptyCart>
  <div>Din kundvagn är tom.</div>
</ng-template>

// react-app/src/components/ShoppingCart.js
import React from 'react';
import { useCart } from '../CartContext';

const ShoppingCart = () => {
  const { removeFromCart, cart } = useCart();

// Funktion för att beräkna det totala priset
const calculateTotalPrice = () => {
  return cart.reduce((total, product) => total + parseFloat(product.price), 0);
};

  return (
    <div>
      {cart.map(product => (
        <div key={product.sku} className="shopping-cart-container">
          <div className="shopping-cart">
            <img
              src={require(`../../../mango/${product.image_downloads[0].replace(/['"\[\]]+/g, '')}.jpg`)}
              alt={`Bild`}
              className="cart-image"
            />
          </div>
          <div className="shopping-product-info">
            <p className="shopping-detail-content">{product.name}</p>
            <p className="shopping-detail-content">Pris: {product.price} {product.currency}</p>
            <button onClick={() => removeFromCart(product.sku)}>Ta bort</button>
          </div>
        </div>
      ))}
      <div className="total-price">
        <p>Totalt pris: {calculateTotalPrice()} {cart.length > 0 ? cart[0].currency : ''}</p>
        <button className="pay-button">Betala</button>
      </div>
    </div>
  );
};

export default ShoppingCart;
