// react-app/src/components/Navigation.js
import React from 'react';

function Navigation() {
    return (
        <nav>
            <ul>
                <li><a href="#">Hem</a></li>
                <li><a href="#">Produkter</a></li>
                <li><a href="#">Om oss</a></li>
                <li><a href="#">Kontakt</a></li>
            </ul>
        </nav>
    );
}

export default Navigation;

// angular-app/src/app/Navigation/navigation.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navigation',
  standalone: true,
  imports: [
    CommonModule
  ],
  templateUrl: './navigation.component.html',
  styleUrl: './navigation.component.css',
})

export class Navigation {
}
<nav>
  <ul>
    <li><a routerLink="/">Hem</a></li>
    <li><a routerLink="/produkter">Produkter</a></li>
    <li><a routerLink="/om-oss">Om oss</a></li>
    <li><a routerLink="/kontakt">Kontakt</a></li>
    <li><a routerLink="/kundvagn"><i class="fa fa-shopping-cart"></i></a></li>
  </ul>
</nav>
