// react-app/src/components/ProductDetail.js
import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';

const ProductDetail = () => {
  const { sku } = useParams();
  const [product, setProduct] = useState(null);

  useEffect(() => {
    fetch(`http://localhost:3001/api/products/${sku}`)
      .then(response => {
        if (!response.ok) {
          throw new Error('Failed to fetch product');
        }
        return response.json();
      })
      .then(data => {
        setProduct(data);
      })
      .catch(error => console.error('Error fetching product details:', error));
  }, [sku]);

  const handleAddToCart = () => {
    alert('Produkten har lagts till i kundvagnen.');
  };

  return (
    <div>
      {product && (
        <div className="product-detail-container">
          <div className="product-details">
            {product.image_downloads.map((image, index) => (
              <img
                key={index}
                src={require(`../../../mango/${image.replace(/['"\[\]]+/g, '')}.jpg`)}
                alt={`Bild ${index + 1}`}
                className="product-detail-image"
              />
            ))}
          </div>
          <div className="product-info">
            <h2 className="product-detail-content">{product.name}</h2>
            <p className="product-detail-content">Beskrivning: {product.description}</p>
            <p className="product-detail-content">Pris: {product.price} {product.currency}</p>
            <button onClick={handleAddToCart} className="button">Lägg till i kundvagnen</button>
            <Link to={`/kundvagn/${sku}`} className="button">Gå till kundvagnen</Link>
          </div>
        </div>
      )}
    </div>
  );
};

export default ProductDetail;

// angular-app/src/app/product-detail/product-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ProductService } from '../product.service';
import { CartService } from '../cart.service';

@Component({
  selector: 'app-product-detail',
  templateUrl: './product-detail.component.html',
  styleUrl: './product-detail.component.css'
})

export class ProductDetailComponent implements OnInit {
  product: any;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private productService: ProductService,
    private cartService: CartService
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      const sku = params['sku'];
      this.productService.getProduct(sku).subscribe((data: any) => {
        // Manipulera bildsträngen här för att rensa bort oönskade tecken
        data.image_downloads = data.image_downloads.map((image: string) => {
          return image.replace(/[\'\"\[\]]+/g, '');
        });
        this.product = data;
      }, error => {
        console.error('Error fetching product details:', error);
      });
    });
  }

  addToCart(): void {
    const sku = this.product.sku;
    this.cartService.addToCart(this.product, sku);
    alert('Produkten har lagts till i kundvagnen.');
  }
}

<div *ngIf="product" class="product-detail-container">
  <div class="product-details">
    <img *ngFor="let image of product.image_downloads" [src]="'./assets/mango/' + image + '.jpg'" [alt]="image" class="product-detail-image">
  </div>
  <div class="product-info">
    <h2 class="product-detail-content">{{ product.name }}</h2>
    <p class="product-detail-content">Beskrivning: {{ product.description }}</p>
    <p class="product-detail-content">Pris: {{ product.price }} {{ product.currency }}</p>
    <button (click)="addToCart()" class="button">Lägg till i kundvagnen</button>
    <a routerLink="/shopping-cart/" class="button">Gå till kundvagnen</a>
  </div>
</div>
